// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// FacetsColumns holds the columns for the "facets" table.
	FacetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "session_id", Type: field.TypeString},
		{Name: "facets", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
	}
	// FacetsTable holds the schema information for the "facets" table.
	FacetsTable = &schema.Table{
		Name:       "facets",
		Columns:    FacetsColumns,
		PrimaryKey: []*schema.Column{FacetsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "facet_session_id",
				Unique:  true,
				Columns: []*schema.Column{FacetsColumns[1]},
			},
		},
	}
	// NodesColumns holds the columns for the "nodes" table.
	NodesColumns = []*schema.Column{
		{Name: "hash", Type: field.TypeString, Unique: true},
		{Name: "bucket", Type: field.TypeJSON, Nullable: true},
		{Name: "type", Type: field.TypeString, Nullable: true},
		{Name: "role", Type: field.TypeString, Nullable: true},
		{Name: "content", Type: field.TypeJSON, Nullable: true},
		{Name: "model", Type: field.TypeString, Nullable: true},
		{Name: "provider", Type: field.TypeString, Nullable: true},
		{Name: "agent_name", Type: field.TypeString, Nullable: true},
		{Name: "stop_reason", Type: field.TypeString, Nullable: true},
		{Name: "prompt_tokens", Type: field.TypeInt, Nullable: true},
		{Name: "completion_tokens", Type: field.TypeInt, Nullable: true},
		{Name: "total_tokens", Type: field.TypeInt, Nullable: true},
		{Name: "cache_creation_input_tokens", Type: field.TypeInt, Nullable: true},
		{Name: "cache_read_input_tokens", Type: field.TypeInt, Nullable: true},
		{Name: "total_duration_ns", Type: field.TypeInt64, Nullable: true},
		{Name: "prompt_duration_ns", Type: field.TypeInt64, Nullable: true},
		{Name: "project", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "parent_hash", Type: field.TypeString, Nullable: true},
	}
	// NodesTable holds the schema information for the "nodes" table.
	NodesTable = &schema.Table{
		Name:       "nodes",
		Columns:    NodesColumns,
		PrimaryKey: []*schema.Column{NodesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "nodes_nodes_parent",
				Columns:    []*schema.Column{NodesColumns[18]},
				RefColumns: []*schema.Column{NodesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "node_parent_hash",
				Unique:  false,
				Columns: []*schema.Column{NodesColumns[18]},
			},
			{
				Name:    "node_role",
				Unique:  false,
				Columns: []*schema.Column{NodesColumns[3]},
			},
			{
				Name:    "node_model",
				Unique:  false,
				Columns: []*schema.Column{NodesColumns[5]},
			},
			{
				Name:    "node_provider",
				Unique:  false,
				Columns: []*schema.Column{NodesColumns[6]},
			},
			{
				Name:    "node_agent_name",
				Unique:  false,
				Columns: []*schema.Column{NodesColumns[7]},
			},
			{
				Name:    "node_role_model",
				Unique:  false,
				Columns: []*schema.Column{NodesColumns[3], NodesColumns[5]},
			},
			{
				Name:    "node_project",
				Unique:  false,
				Columns: []*schema.Column{NodesColumns[16]},
			},
			{
				Name:    "node_created_at",
				Unique:  false,
				Columns: []*schema.Column{NodesColumns[17]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FacetsTable,
		NodesTable,
	}
)

func init() {
	NodesTable.ForeignKeys[0].RefTable = NodesTable
}
