// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/papercomputeco/tapes/pkg/storage/ent/node"
	"github.com/papercomputeco/tapes/pkg/storage/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeNode = "Node"
)

// NodeMutation represents an operation that mutates the Node nodes in the graph.
type NodeMutation struct {
	config
	op                             Op
	typ                            string
	id                             *string
	bucket                         *map[string]interface{}
	_type                          *string
	role                           *string
	content                        *[]map[string]interface{}
	appendcontent                  []map[string]interface{}
	model                          *string
	provider                       *string
	agent_name                     *string
	stop_reason                    *string
	prompt_tokens                  *int
	addprompt_tokens               *int
	completion_tokens              *int
	addcompletion_tokens           *int
	total_tokens                   *int
	addtotal_tokens                *int
	cache_creation_input_tokens    *int
	addcache_creation_input_tokens *int
	cache_read_input_tokens        *int
	addcache_read_input_tokens     *int
	total_duration_ns              *int64
	addtotal_duration_ns           *int64
	prompt_duration_ns             *int64
	addprompt_duration_ns          *int64
	project                        *string
	created_at                     *time.Time
	clearedFields                  map[string]struct{}
	parent                         *string
	clearedparent                  bool
	children                       map[string]struct{}
	removedchildren                map[string]struct{}
	clearedchildren                bool
	done                           bool
	oldValue                       func(context.Context) (*Node, error)
	predicates                     []predicate.Node
}

var _ ent.Mutation = (*NodeMutation)(nil)

// nodeOption allows management of the mutation configuration using functional options.
type nodeOption func(*NodeMutation)

// newNodeMutation creates new mutation for the Node entity.
func newNodeMutation(c config, op Op, opts ...nodeOption) *NodeMutation {
	m := &NodeMutation{
		config:        c,
		op:            op,
		typ:           TypeNode,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withNodeID sets the ID field of the mutation.
func withNodeID(id string) nodeOption {
	return func(m *NodeMutation) {
		var (
			err   error
			once  sync.Once
			value *Node
		)
		m.oldValue = func(ctx context.Context) (*Node, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Node.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withNode sets the old Node of the mutation.
func withNode(node *Node) nodeOption {
	return func(m *NodeMutation) {
		m.oldValue = func(context.Context) (*Node, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m NodeMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m NodeMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Node entities.
func (m *NodeMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *NodeMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *NodeMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Node.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetParentHash sets the "parent_hash" field.
func (m *NodeMutation) SetParentHash(s string) {
	m.parent = &s
}

// ParentHash returns the value of the "parent_hash" field in the mutation.
func (m *NodeMutation) ParentHash() (r string, exists bool) {
	v := m.parent
	if v == nil {
		return
	}
	return *v, true
}

// OldParentHash returns the old "parent_hash" field's value of the Node entity.
// If the Node object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NodeMutation) OldParentHash(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldParentHash is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldParentHash requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldParentHash: %w", err)
	}
	return oldValue.ParentHash, nil
}

// ClearParentHash clears the value of the "parent_hash" field.
func (m *NodeMutation) ClearParentHash() {
	m.parent = nil
	m.clearedFields[node.FieldParentHash] = struct{}{}
}

// ParentHashCleared returns if the "parent_hash" field was cleared in this mutation.
func (m *NodeMutation) ParentHashCleared() bool {
	_, ok := m.clearedFields[node.FieldParentHash]
	return ok
}

// ResetParentHash resets all changes to the "parent_hash" field.
func (m *NodeMutation) ResetParentHash() {
	m.parent = nil
	delete(m.clearedFields, node.FieldParentHash)
}

// SetBucket sets the "bucket" field.
func (m *NodeMutation) SetBucket(value map[string]interface{}) {
	m.bucket = &value
}

// Bucket returns the value of the "bucket" field in the mutation.
func (m *NodeMutation) Bucket() (r map[string]interface{}, exists bool) {
	v := m.bucket
	if v == nil {
		return
	}
	return *v, true
}

// OldBucket returns the old "bucket" field's value of the Node entity.
// If the Node object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NodeMutation) OldBucket(ctx context.Context) (v map[string]interface{}, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBucket is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBucket requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBucket: %w", err)
	}
	return oldValue.Bucket, nil
}

// ClearBucket clears the value of the "bucket" field.
func (m *NodeMutation) ClearBucket() {
	m.bucket = nil
	m.clearedFields[node.FieldBucket] = struct{}{}
}

// BucketCleared returns if the "bucket" field was cleared in this mutation.
func (m *NodeMutation) BucketCleared() bool {
	_, ok := m.clearedFields[node.FieldBucket]
	return ok
}

// ResetBucket resets all changes to the "bucket" field.
func (m *NodeMutation) ResetBucket() {
	m.bucket = nil
	delete(m.clearedFields, node.FieldBucket)
}

// SetType sets the "type" field.
func (m *NodeMutation) SetType(s string) {
	m._type = &s
}

// GetType returns the value of the "type" field in the mutation.
func (m *NodeMutation) GetType() (r string, exists bool) {
	v := m._type
	if v == nil {
		return
	}
	return *v, true
}

// OldType returns the old "type" field's value of the Node entity.
// If the Node object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NodeMutation) OldType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldType: %w", err)
	}
	return oldValue.Type, nil
}

// ClearType clears the value of the "type" field.
func (m *NodeMutation) ClearType() {
	m._type = nil
	m.clearedFields[node.FieldType] = struct{}{}
}

// TypeCleared returns if the "type" field was cleared in this mutation.
func (m *NodeMutation) TypeCleared() bool {
	_, ok := m.clearedFields[node.FieldType]
	return ok
}

// ResetType resets all changes to the "type" field.
func (m *NodeMutation) ResetType() {
	m._type = nil
	delete(m.clearedFields, node.FieldType)
}

// SetRole sets the "role" field.
func (m *NodeMutation) SetRole(s string) {
	m.role = &s
}

// Role returns the value of the "role" field in the mutation.
func (m *NodeMutation) Role() (r string, exists bool) {
	v := m.role
	if v == nil {
		return
	}
	return *v, true
}

// OldRole returns the old "role" field's value of the Node entity.
// If the Node object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NodeMutation) OldRole(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRole is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRole requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRole: %w", err)
	}
	return oldValue.Role, nil
}

// ClearRole clears the value of the "role" field.
func (m *NodeMutation) ClearRole() {
	m.role = nil
	m.clearedFields[node.FieldRole] = struct{}{}
}

// RoleCleared returns if the "role" field was cleared in this mutation.
func (m *NodeMutation) RoleCleared() bool {
	_, ok := m.clearedFields[node.FieldRole]
	return ok
}

// ResetRole resets all changes to the "role" field.
func (m *NodeMutation) ResetRole() {
	m.role = nil
	delete(m.clearedFields, node.FieldRole)
}

// SetContent sets the "content" field.
func (m *NodeMutation) SetContent(value []map[string]interface{}) {
	m.content = &value
	m.appendcontent = nil
}

// Content returns the value of the "content" field in the mutation.
func (m *NodeMutation) Content() (r []map[string]interface{}, exists bool) {
	v := m.content
	if v == nil {
		return
	}
	return *v, true
}

// OldContent returns the old "content" field's value of the Node entity.
// If the Node object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NodeMutation) OldContent(ctx context.Context) (v []map[string]interface{}, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldContent is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldContent requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldContent: %w", err)
	}
	return oldValue.Content, nil
}

// AppendContent adds value to the "content" field.
func (m *NodeMutation) AppendContent(value []map[string]interface{}) {
	m.appendcontent = append(m.appendcontent, value...)
}

// AppendedContent returns the list of values that were appended to the "content" field in this mutation.
func (m *NodeMutation) AppendedContent() ([]map[string]interface{}, bool) {
	if len(m.appendcontent) == 0 {
		return nil, false
	}
	return m.appendcontent, true
}

// ClearContent clears the value of the "content" field.
func (m *NodeMutation) ClearContent() {
	m.content = nil
	m.appendcontent = nil
	m.clearedFields[node.FieldContent] = struct{}{}
}

// ContentCleared returns if the "content" field was cleared in this mutation.
func (m *NodeMutation) ContentCleared() bool {
	_, ok := m.clearedFields[node.FieldContent]
	return ok
}

// ResetContent resets all changes to the "content" field.
func (m *NodeMutation) ResetContent() {
	m.content = nil
	m.appendcontent = nil
	delete(m.clearedFields, node.FieldContent)
}

// SetModel sets the "model" field.
func (m *NodeMutation) SetModel(s string) {
	m.model = &s
}

// Model returns the value of the "model" field in the mutation.
func (m *NodeMutation) Model() (r string, exists bool) {
	v := m.model
	if v == nil {
		return
	}
	return *v, true
}

// OldModel returns the old "model" field's value of the Node entity.
// If the Node object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NodeMutation) OldModel(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldModel is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldModel requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldModel: %w", err)
	}
	return oldValue.Model, nil
}

// ClearModel clears the value of the "model" field.
func (m *NodeMutation) ClearModel() {
	m.model = nil
	m.clearedFields[node.FieldModel] = struct{}{}
}

// ModelCleared returns if the "model" field was cleared in this mutation.
func (m *NodeMutation) ModelCleared() bool {
	_, ok := m.clearedFields[node.FieldModel]
	return ok
}

// ResetModel resets all changes to the "model" field.
func (m *NodeMutation) ResetModel() {
	m.model = nil
	delete(m.clearedFields, node.FieldModel)
}

// SetProvider sets the "provider" field.
func (m *NodeMutation) SetProvider(s string) {
	m.provider = &s
}

// Provider returns the value of the "provider" field in the mutation.
func (m *NodeMutation) Provider() (r string, exists bool) {
	v := m.provider
	if v == nil {
		return
	}
	return *v, true
}

// OldProvider returns the old "provider" field's value of the Node entity.
// If the Node object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NodeMutation) OldProvider(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProvider is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProvider requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProvider: %w", err)
	}
	return oldValue.Provider, nil
}

// ClearProvider clears the value of the "provider" field.
func (m *NodeMutation) ClearProvider() {
	m.provider = nil
	m.clearedFields[node.FieldProvider] = struct{}{}
}

// ProviderCleared returns if the "provider" field was cleared in this mutation.
func (m *NodeMutation) ProviderCleared() bool {
	_, ok := m.clearedFields[node.FieldProvider]
	return ok
}

// ResetProvider resets all changes to the "provider" field.
func (m *NodeMutation) ResetProvider() {
	m.provider = nil
	delete(m.clearedFields, node.FieldProvider)
}

// SetAgentName sets the "agent_name" field.
func (m *NodeMutation) SetAgentName(s string) {
	m.agent_name = &s
}

// AgentName returns the value of the "agent_name" field in the mutation.
func (m *NodeMutation) AgentName() (r string, exists bool) {
	v := m.agent_name
	if v == nil {
		return
	}
	return *v, true
}

// OldAgentName returns the old "agent_name" field's value of the Node entity.
// If the Node object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NodeMutation) OldAgentName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAgentName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAgentName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAgentName: %w", err)
	}
	return oldValue.AgentName, nil
}

// ClearAgentName clears the value of the "agent_name" field.
func (m *NodeMutation) ClearAgentName() {
	m.agent_name = nil
	m.clearedFields[node.FieldAgentName] = struct{}{}
}

// AgentNameCleared returns if the "agent_name" field was cleared in this mutation.
func (m *NodeMutation) AgentNameCleared() bool {
	_, ok := m.clearedFields[node.FieldAgentName]
	return ok
}

// ResetAgentName resets all changes to the "agent_name" field.
func (m *NodeMutation) ResetAgentName() {
	m.agent_name = nil
	delete(m.clearedFields, node.FieldAgentName)
}

// SetStopReason sets the "stop_reason" field.
func (m *NodeMutation) SetStopReason(s string) {
	m.stop_reason = &s
}

// StopReason returns the value of the "stop_reason" field in the mutation.
func (m *NodeMutation) StopReason() (r string, exists bool) {
	v := m.stop_reason
	if v == nil {
		return
	}
	return *v, true
}

// OldStopReason returns the old "stop_reason" field's value of the Node entity.
// If the Node object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NodeMutation) OldStopReason(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStopReason is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStopReason requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStopReason: %w", err)
	}
	return oldValue.StopReason, nil
}

// ClearStopReason clears the value of the "stop_reason" field.
func (m *NodeMutation) ClearStopReason() {
	m.stop_reason = nil
	m.clearedFields[node.FieldStopReason] = struct{}{}
}

// StopReasonCleared returns if the "stop_reason" field was cleared in this mutation.
func (m *NodeMutation) StopReasonCleared() bool {
	_, ok := m.clearedFields[node.FieldStopReason]
	return ok
}

// ResetStopReason resets all changes to the "stop_reason" field.
func (m *NodeMutation) ResetStopReason() {
	m.stop_reason = nil
	delete(m.clearedFields, node.FieldStopReason)
}

// SetPromptTokens sets the "prompt_tokens" field.
func (m *NodeMutation) SetPromptTokens(i int) {
	m.prompt_tokens = &i
	m.addprompt_tokens = nil
}

// PromptTokens returns the value of the "prompt_tokens" field in the mutation.
func (m *NodeMutation) PromptTokens() (r int, exists bool) {
	v := m.prompt_tokens
	if v == nil {
		return
	}
	return *v, true
}

// OldPromptTokens returns the old "prompt_tokens" field's value of the Node entity.
// If the Node object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NodeMutation) OldPromptTokens(ctx context.Context) (v *int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPromptTokens is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPromptTokens requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPromptTokens: %w", err)
	}
	return oldValue.PromptTokens, nil
}

// AddPromptTokens adds i to the "prompt_tokens" field.
func (m *NodeMutation) AddPromptTokens(i int) {
	if m.addprompt_tokens != nil {
		*m.addprompt_tokens += i
	} else {
		m.addprompt_tokens = &i
	}
}

// AddedPromptTokens returns the value that was added to the "prompt_tokens" field in this mutation.
func (m *NodeMutation) AddedPromptTokens() (r int, exists bool) {
	v := m.addprompt_tokens
	if v == nil {
		return
	}
	return *v, true
}

// ClearPromptTokens clears the value of the "prompt_tokens" field.
func (m *NodeMutation) ClearPromptTokens() {
	m.prompt_tokens = nil
	m.addprompt_tokens = nil
	m.clearedFields[node.FieldPromptTokens] = struct{}{}
}

// PromptTokensCleared returns if the "prompt_tokens" field was cleared in this mutation.
func (m *NodeMutation) PromptTokensCleared() bool {
	_, ok := m.clearedFields[node.FieldPromptTokens]
	return ok
}

// ResetPromptTokens resets all changes to the "prompt_tokens" field.
func (m *NodeMutation) ResetPromptTokens() {
	m.prompt_tokens = nil
	m.addprompt_tokens = nil
	delete(m.clearedFields, node.FieldPromptTokens)
}

// SetCompletionTokens sets the "completion_tokens" field.
func (m *NodeMutation) SetCompletionTokens(i int) {
	m.completion_tokens = &i
	m.addcompletion_tokens = nil
}

// CompletionTokens returns the value of the "completion_tokens" field in the mutation.
func (m *NodeMutation) CompletionTokens() (r int, exists bool) {
	v := m.completion_tokens
	if v == nil {
		return
	}
	return *v, true
}

// OldCompletionTokens returns the old "completion_tokens" field's value of the Node entity.
// If the Node object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NodeMutation) OldCompletionTokens(ctx context.Context) (v *int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCompletionTokens is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCompletionTokens requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCompletionTokens: %w", err)
	}
	return oldValue.CompletionTokens, nil
}

// AddCompletionTokens adds i to the "completion_tokens" field.
func (m *NodeMutation) AddCompletionTokens(i int) {
	if m.addcompletion_tokens != nil {
		*m.addcompletion_tokens += i
	} else {
		m.addcompletion_tokens = &i
	}
}

// AddedCompletionTokens returns the value that was added to the "completion_tokens" field in this mutation.
func (m *NodeMutation) AddedCompletionTokens() (r int, exists bool) {
	v := m.addcompletion_tokens
	if v == nil {
		return
	}
	return *v, true
}

// ClearCompletionTokens clears the value of the "completion_tokens" field.
func (m *NodeMutation) ClearCompletionTokens() {
	m.completion_tokens = nil
	m.addcompletion_tokens = nil
	m.clearedFields[node.FieldCompletionTokens] = struct{}{}
}

// CompletionTokensCleared returns if the "completion_tokens" field was cleared in this mutation.
func (m *NodeMutation) CompletionTokensCleared() bool {
	_, ok := m.clearedFields[node.FieldCompletionTokens]
	return ok
}

// ResetCompletionTokens resets all changes to the "completion_tokens" field.
func (m *NodeMutation) ResetCompletionTokens() {
	m.completion_tokens = nil
	m.addcompletion_tokens = nil
	delete(m.clearedFields, node.FieldCompletionTokens)
}

// SetTotalTokens sets the "total_tokens" field.
func (m *NodeMutation) SetTotalTokens(i int) {
	m.total_tokens = &i
	m.addtotal_tokens = nil
}

// TotalTokens returns the value of the "total_tokens" field in the mutation.
func (m *NodeMutation) TotalTokens() (r int, exists bool) {
	v := m.total_tokens
	if v == nil {
		return
	}
	return *v, true
}

// OldTotalTokens returns the old "total_tokens" field's value of the Node entity.
// If the Node object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NodeMutation) OldTotalTokens(ctx context.Context) (v *int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTotalTokens is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTotalTokens requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTotalTokens: %w", err)
	}
	return oldValue.TotalTokens, nil
}

// AddTotalTokens adds i to the "total_tokens" field.
func (m *NodeMutation) AddTotalTokens(i int) {
	if m.addtotal_tokens != nil {
		*m.addtotal_tokens += i
	} else {
		m.addtotal_tokens = &i
	}
}

// AddedTotalTokens returns the value that was added to the "total_tokens" field in this mutation.
func (m *NodeMutation) AddedTotalTokens() (r int, exists bool) {
	v := m.addtotal_tokens
	if v == nil {
		return
	}
	return *v, true
}

// ClearTotalTokens clears the value of the "total_tokens" field.
func (m *NodeMutation) ClearTotalTokens() {
	m.total_tokens = nil
	m.addtotal_tokens = nil
	m.clearedFields[node.FieldTotalTokens] = struct{}{}
}

// TotalTokensCleared returns if the "total_tokens" field was cleared in this mutation.
func (m *NodeMutation) TotalTokensCleared() bool {
	_, ok := m.clearedFields[node.FieldTotalTokens]
	return ok
}

// ResetTotalTokens resets all changes to the "total_tokens" field.
func (m *NodeMutation) ResetTotalTokens() {
	m.total_tokens = nil
	m.addtotal_tokens = nil
	delete(m.clearedFields, node.FieldTotalTokens)
}

// SetCacheCreationInputTokens sets the "cache_creation_input_tokens" field.
func (m *NodeMutation) SetCacheCreationInputTokens(i int) {
	m.cache_creation_input_tokens = &i
	m.addcache_creation_input_tokens = nil
}

// CacheCreationInputTokens returns the value of the "cache_creation_input_tokens" field in the mutation.
func (m *NodeMutation) CacheCreationInputTokens() (r int, exists bool) {
	v := m.cache_creation_input_tokens
	if v == nil {
		return
	}
	return *v, true
}

// OldCacheCreationInputTokens returns the old "cache_creation_input_tokens" field's value of the Node entity.
// If the Node object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NodeMutation) OldCacheCreationInputTokens(ctx context.Context) (v *int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCacheCreationInputTokens is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCacheCreationInputTokens requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCacheCreationInputTokens: %w", err)
	}
	return oldValue.CacheCreationInputTokens, nil
}

// AddCacheCreationInputTokens adds i to the "cache_creation_input_tokens" field.
func (m *NodeMutation) AddCacheCreationInputTokens(i int) {
	if m.addcache_creation_input_tokens != nil {
		*m.addcache_creation_input_tokens += i
	} else {
		m.addcache_creation_input_tokens = &i
	}
}

// AddedCacheCreationInputTokens returns the value that was added to the "cache_creation_input_tokens" field in this mutation.
func (m *NodeMutation) AddedCacheCreationInputTokens() (r int, exists bool) {
	v := m.addcache_creation_input_tokens
	if v == nil {
		return
	}
	return *v, true
}

// ClearCacheCreationInputTokens clears the value of the "cache_creation_input_tokens" field.
func (m *NodeMutation) ClearCacheCreationInputTokens() {
	m.cache_creation_input_tokens = nil
	m.addcache_creation_input_tokens = nil
	m.clearedFields[node.FieldCacheCreationInputTokens] = struct{}{}
}

// CacheCreationInputTokensCleared returns if the "cache_creation_input_tokens" field was cleared in this mutation.
func (m *NodeMutation) CacheCreationInputTokensCleared() bool {
	_, ok := m.clearedFields[node.FieldCacheCreationInputTokens]
	return ok
}

// ResetCacheCreationInputTokens resets all changes to the "cache_creation_input_tokens" field.
func (m *NodeMutation) ResetCacheCreationInputTokens() {
	m.cache_creation_input_tokens = nil
	m.addcache_creation_input_tokens = nil
	delete(m.clearedFields, node.FieldCacheCreationInputTokens)
}

// SetCacheReadInputTokens sets the "cache_read_input_tokens" field.
func (m *NodeMutation) SetCacheReadInputTokens(i int) {
	m.cache_read_input_tokens = &i
	m.addcache_read_input_tokens = nil
}

// CacheReadInputTokens returns the value of the "cache_read_input_tokens" field in the mutation.
func (m *NodeMutation) CacheReadInputTokens() (r int, exists bool) {
	v := m.cache_read_input_tokens
	if v == nil {
		return
	}
	return *v, true
}

// OldCacheReadInputTokens returns the old "cache_read_input_tokens" field's value of the Node entity.
// If the Node object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NodeMutation) OldCacheReadInputTokens(ctx context.Context) (v *int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCacheReadInputTokens is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCacheReadInputTokens requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCacheReadInputTokens: %w", err)
	}
	return oldValue.CacheReadInputTokens, nil
}

// AddCacheReadInputTokens adds i to the "cache_read_input_tokens" field.
func (m *NodeMutation) AddCacheReadInputTokens(i int) {
	if m.addcache_read_input_tokens != nil {
		*m.addcache_read_input_tokens += i
	} else {
		m.addcache_read_input_tokens = &i
	}
}

// AddedCacheReadInputTokens returns the value that was added to the "cache_read_input_tokens" field in this mutation.
func (m *NodeMutation) AddedCacheReadInputTokens() (r int, exists bool) {
	v := m.addcache_read_input_tokens
	if v == nil {
		return
	}
	return *v, true
}

// ClearCacheReadInputTokens clears the value of the "cache_read_input_tokens" field.
func (m *NodeMutation) ClearCacheReadInputTokens() {
	m.cache_read_input_tokens = nil
	m.addcache_read_input_tokens = nil
	m.clearedFields[node.FieldCacheReadInputTokens] = struct{}{}
}

// CacheReadInputTokensCleared returns if the "cache_read_input_tokens" field was cleared in this mutation.
func (m *NodeMutation) CacheReadInputTokensCleared() bool {
	_, ok := m.clearedFields[node.FieldCacheReadInputTokens]
	return ok
}

// ResetCacheReadInputTokens resets all changes to the "cache_read_input_tokens" field.
func (m *NodeMutation) ResetCacheReadInputTokens() {
	m.cache_read_input_tokens = nil
	m.addcache_read_input_tokens = nil
	delete(m.clearedFields, node.FieldCacheReadInputTokens)
}

// SetTotalDurationNs sets the "total_duration_ns" field.
func (m *NodeMutation) SetTotalDurationNs(i int64) {
	m.total_duration_ns = &i
	m.addtotal_duration_ns = nil
}

// TotalDurationNs returns the value of the "total_duration_ns" field in the mutation.
func (m *NodeMutation) TotalDurationNs() (r int64, exists bool) {
	v := m.total_duration_ns
	if v == nil {
		return
	}
	return *v, true
}

// OldTotalDurationNs returns the old "total_duration_ns" field's value of the Node entity.
// If the Node object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NodeMutation) OldTotalDurationNs(ctx context.Context) (v *int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTotalDurationNs is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTotalDurationNs requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTotalDurationNs: %w", err)
	}
	return oldValue.TotalDurationNs, nil
}

// AddTotalDurationNs adds i to the "total_duration_ns" field.
func (m *NodeMutation) AddTotalDurationNs(i int64) {
	if m.addtotal_duration_ns != nil {
		*m.addtotal_duration_ns += i
	} else {
		m.addtotal_duration_ns = &i
	}
}

// AddedTotalDurationNs returns the value that was added to the "total_duration_ns" field in this mutation.
func (m *NodeMutation) AddedTotalDurationNs() (r int64, exists bool) {
	v := m.addtotal_duration_ns
	if v == nil {
		return
	}
	return *v, true
}

// ClearTotalDurationNs clears the value of the "total_duration_ns" field.
func (m *NodeMutation) ClearTotalDurationNs() {
	m.total_duration_ns = nil
	m.addtotal_duration_ns = nil
	m.clearedFields[node.FieldTotalDurationNs] = struct{}{}
}

// TotalDurationNsCleared returns if the "total_duration_ns" field was cleared in this mutation.
func (m *NodeMutation) TotalDurationNsCleared() bool {
	_, ok := m.clearedFields[node.FieldTotalDurationNs]
	return ok
}

// ResetTotalDurationNs resets all changes to the "total_duration_ns" field.
func (m *NodeMutation) ResetTotalDurationNs() {
	m.total_duration_ns = nil
	m.addtotal_duration_ns = nil
	delete(m.clearedFields, node.FieldTotalDurationNs)
}

// SetPromptDurationNs sets the "prompt_duration_ns" field.
func (m *NodeMutation) SetPromptDurationNs(i int64) {
	m.prompt_duration_ns = &i
	m.addprompt_duration_ns = nil
}

// PromptDurationNs returns the value of the "prompt_duration_ns" field in the mutation.
func (m *NodeMutation) PromptDurationNs() (r int64, exists bool) {
	v := m.prompt_duration_ns
	if v == nil {
		return
	}
	return *v, true
}

// OldPromptDurationNs returns the old "prompt_duration_ns" field's value of the Node entity.
// If the Node object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NodeMutation) OldPromptDurationNs(ctx context.Context) (v *int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPromptDurationNs is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPromptDurationNs requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPromptDurationNs: %w", err)
	}
	return oldValue.PromptDurationNs, nil
}

// AddPromptDurationNs adds i to the "prompt_duration_ns" field.
func (m *NodeMutation) AddPromptDurationNs(i int64) {
	if m.addprompt_duration_ns != nil {
		*m.addprompt_duration_ns += i
	} else {
		m.addprompt_duration_ns = &i
	}
}

// AddedPromptDurationNs returns the value that was added to the "prompt_duration_ns" field in this mutation.
func (m *NodeMutation) AddedPromptDurationNs() (r int64, exists bool) {
	v := m.addprompt_duration_ns
	if v == nil {
		return
	}
	return *v, true
}

// ClearPromptDurationNs clears the value of the "prompt_duration_ns" field.
func (m *NodeMutation) ClearPromptDurationNs() {
	m.prompt_duration_ns = nil
	m.addprompt_duration_ns = nil
	m.clearedFields[node.FieldPromptDurationNs] = struct{}{}
}

// PromptDurationNsCleared returns if the "prompt_duration_ns" field was cleared in this mutation.
func (m *NodeMutation) PromptDurationNsCleared() bool {
	_, ok := m.clearedFields[node.FieldPromptDurationNs]
	return ok
}

// ResetPromptDurationNs resets all changes to the "prompt_duration_ns" field.
func (m *NodeMutation) ResetPromptDurationNs() {
	m.prompt_duration_ns = nil
	m.addprompt_duration_ns = nil
	delete(m.clearedFields, node.FieldPromptDurationNs)
}

// SetProject sets the "project" field.
func (m *NodeMutation) SetProject(s string) {
	m.project = &s
}

// Project returns the value of the "project" field in the mutation.
func (m *NodeMutation) Project() (r string, exists bool) {
	v := m.project
	if v == nil {
		return
	}
	return *v, true
}

// OldProject returns the old "project" field's value of the Node entity.
// If the Node object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NodeMutation) OldProject(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProject is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProject requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProject: %w", err)
	}
	return oldValue.Project, nil
}

// ClearProject clears the value of the "project" field.
func (m *NodeMutation) ClearProject() {
	m.project = nil
	m.clearedFields[node.FieldProject] = struct{}{}
}

// ProjectCleared returns if the "project" field was cleared in this mutation.
func (m *NodeMutation) ProjectCleared() bool {
	_, ok := m.clearedFields[node.FieldProject]
	return ok
}

// ResetProject resets all changes to the "project" field.
func (m *NodeMutation) ResetProject() {
	m.project = nil
	delete(m.clearedFields, node.FieldProject)
}

// SetCreatedAt sets the "created_at" field.
func (m *NodeMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *NodeMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Node entity.
// If the Node object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NodeMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *NodeMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetParentID sets the "parent" edge to the Node entity by id.
func (m *NodeMutation) SetParentID(id string) {
	m.parent = &id
}

// ClearParent clears the "parent" edge to the Node entity.
func (m *NodeMutation) ClearParent() {
	m.clearedparent = true
	m.clearedFields[node.FieldParentHash] = struct{}{}
}

// ParentCleared reports if the "parent" edge to the Node entity was cleared.
func (m *NodeMutation) ParentCleared() bool {
	return m.ParentHashCleared() || m.clearedparent
}

// ParentID returns the "parent" edge ID in the mutation.
func (m *NodeMutation) ParentID() (id string, exists bool) {
	if m.parent != nil {
		return *m.parent, true
	}
	return
}

// ParentIDs returns the "parent" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// ParentID instead. It exists only for internal usage by the builders.
func (m *NodeMutation) ParentIDs() (ids []string) {
	if id := m.parent; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetParent resets all changes to the "parent" edge.
func (m *NodeMutation) ResetParent() {
	m.parent = nil
	m.clearedparent = false
}

// AddChildIDs adds the "children" edge to the Node entity by ids.
func (m *NodeMutation) AddChildIDs(ids ...string) {
	if m.children == nil {
		m.children = make(map[string]struct{})
	}
	for i := range ids {
		m.children[ids[i]] = struct{}{}
	}
}

// ClearChildren clears the "children" edge to the Node entity.
func (m *NodeMutation) ClearChildren() {
	m.clearedchildren = true
}

// ChildrenCleared reports if the "children" edge to the Node entity was cleared.
func (m *NodeMutation) ChildrenCleared() bool {
	return m.clearedchildren
}

// RemoveChildIDs removes the "children" edge to the Node entity by IDs.
func (m *NodeMutation) RemoveChildIDs(ids ...string) {
	if m.removedchildren == nil {
		m.removedchildren = make(map[string]struct{})
	}
	for i := range ids {
		delete(m.children, ids[i])
		m.removedchildren[ids[i]] = struct{}{}
	}
}

// RemovedChildren returns the removed IDs of the "children" edge to the Node entity.
func (m *NodeMutation) RemovedChildrenIDs() (ids []string) {
	for id := range m.removedchildren {
		ids = append(ids, id)
	}
	return
}

// ChildrenIDs returns the "children" edge IDs in the mutation.
func (m *NodeMutation) ChildrenIDs() (ids []string) {
	for id := range m.children {
		ids = append(ids, id)
	}
	return
}

// ResetChildren resets all changes to the "children" edge.
func (m *NodeMutation) ResetChildren() {
	m.children = nil
	m.clearedchildren = false
	m.removedchildren = nil
}

// Where appends a list predicates to the NodeMutation builder.
func (m *NodeMutation) Where(ps ...predicate.Node) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the NodeMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *NodeMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Node, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *NodeMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *NodeMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Node).
func (m *NodeMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *NodeMutation) Fields() []string {
	fields := make([]string, 0, 18)
	if m.parent != nil {
		fields = append(fields, node.FieldParentHash)
	}
	if m.bucket != nil {
		fields = append(fields, node.FieldBucket)
	}
	if m._type != nil {
		fields = append(fields, node.FieldType)
	}
	if m.role != nil {
		fields = append(fields, node.FieldRole)
	}
	if m.content != nil {
		fields = append(fields, node.FieldContent)
	}
	if m.model != nil {
		fields = append(fields, node.FieldModel)
	}
	if m.provider != nil {
		fields = append(fields, node.FieldProvider)
	}
	if m.agent_name != nil {
		fields = append(fields, node.FieldAgentName)
	}
	if m.stop_reason != nil {
		fields = append(fields, node.FieldStopReason)
	}
	if m.prompt_tokens != nil {
		fields = append(fields, node.FieldPromptTokens)
	}
	if m.completion_tokens != nil {
		fields = append(fields, node.FieldCompletionTokens)
	}
	if m.total_tokens != nil {
		fields = append(fields, node.FieldTotalTokens)
	}
	if m.cache_creation_input_tokens != nil {
		fields = append(fields, node.FieldCacheCreationInputTokens)
	}
	if m.cache_read_input_tokens != nil {
		fields = append(fields, node.FieldCacheReadInputTokens)
	}
	if m.total_duration_ns != nil {
		fields = append(fields, node.FieldTotalDurationNs)
	}
	if m.prompt_duration_ns != nil {
		fields = append(fields, node.FieldPromptDurationNs)
	}
	if m.project != nil {
		fields = append(fields, node.FieldProject)
	}
	if m.created_at != nil {
		fields = append(fields, node.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *NodeMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case node.FieldParentHash:
		return m.ParentHash()
	case node.FieldBucket:
		return m.Bucket()
	case node.FieldType:
		return m.GetType()
	case node.FieldRole:
		return m.Role()
	case node.FieldContent:
		return m.Content()
	case node.FieldModel:
		return m.Model()
	case node.FieldProvider:
		return m.Provider()
	case node.FieldAgentName:
		return m.AgentName()
	case node.FieldStopReason:
		return m.StopReason()
	case node.FieldPromptTokens:
		return m.PromptTokens()
	case node.FieldCompletionTokens:
		return m.CompletionTokens()
	case node.FieldTotalTokens:
		return m.TotalTokens()
	case node.FieldCacheCreationInputTokens:
		return m.CacheCreationInputTokens()
	case node.FieldCacheReadInputTokens:
		return m.CacheReadInputTokens()
	case node.FieldTotalDurationNs:
		return m.TotalDurationNs()
	case node.FieldPromptDurationNs:
		return m.PromptDurationNs()
	case node.FieldProject:
		return m.Project()
	case node.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *NodeMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case node.FieldParentHash:
		return m.OldParentHash(ctx)
	case node.FieldBucket:
		return m.OldBucket(ctx)
	case node.FieldType:
		return m.OldType(ctx)
	case node.FieldRole:
		return m.OldRole(ctx)
	case node.FieldContent:
		return m.OldContent(ctx)
	case node.FieldModel:
		return m.OldModel(ctx)
	case node.FieldProvider:
		return m.OldProvider(ctx)
	case node.FieldAgentName:
		return m.OldAgentName(ctx)
	case node.FieldStopReason:
		return m.OldStopReason(ctx)
	case node.FieldPromptTokens:
		return m.OldPromptTokens(ctx)
	case node.FieldCompletionTokens:
		return m.OldCompletionTokens(ctx)
	case node.FieldTotalTokens:
		return m.OldTotalTokens(ctx)
	case node.FieldCacheCreationInputTokens:
		return m.OldCacheCreationInputTokens(ctx)
	case node.FieldCacheReadInputTokens:
		return m.OldCacheReadInputTokens(ctx)
	case node.FieldTotalDurationNs:
		return m.OldTotalDurationNs(ctx)
	case node.FieldPromptDurationNs:
		return m.OldPromptDurationNs(ctx)
	case node.FieldProject:
		return m.OldProject(ctx)
	case node.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Node field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *NodeMutation) SetField(name string, value ent.Value) error {
	switch name {
	case node.FieldParentHash:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetParentHash(v)
		return nil
	case node.FieldBucket:
		v, ok := value.(map[string]interface{})
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBucket(v)
		return nil
	case node.FieldType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetType(v)
		return nil
	case node.FieldRole:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRole(v)
		return nil
	case node.FieldContent:
		v, ok := value.([]map[string]interface{})
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetContent(v)
		return nil
	case node.FieldModel:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetModel(v)
		return nil
	case node.FieldProvider:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProvider(v)
		return nil
	case node.FieldAgentName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAgentName(v)
		return nil
	case node.FieldStopReason:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStopReason(v)
		return nil
	case node.FieldPromptTokens:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPromptTokens(v)
		return nil
	case node.FieldCompletionTokens:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCompletionTokens(v)
		return nil
	case node.FieldTotalTokens:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTotalTokens(v)
		return nil
	case node.FieldCacheCreationInputTokens:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCacheCreationInputTokens(v)
		return nil
	case node.FieldCacheReadInputTokens:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCacheReadInputTokens(v)
		return nil
	case node.FieldTotalDurationNs:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTotalDurationNs(v)
		return nil
	case node.FieldPromptDurationNs:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPromptDurationNs(v)
		return nil
	case node.FieldProject:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProject(v)
		return nil
	case node.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Node field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *NodeMutation) AddedFields() []string {
	var fields []string
	if m.addprompt_tokens != nil {
		fields = append(fields, node.FieldPromptTokens)
	}
	if m.addcompletion_tokens != nil {
		fields = append(fields, node.FieldCompletionTokens)
	}
	if m.addtotal_tokens != nil {
		fields = append(fields, node.FieldTotalTokens)
	}
	if m.addcache_creation_input_tokens != nil {
		fields = append(fields, node.FieldCacheCreationInputTokens)
	}
	if m.addcache_read_input_tokens != nil {
		fields = append(fields, node.FieldCacheReadInputTokens)
	}
	if m.addtotal_duration_ns != nil {
		fields = append(fields, node.FieldTotalDurationNs)
	}
	if m.addprompt_duration_ns != nil {
		fields = append(fields, node.FieldPromptDurationNs)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *NodeMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case node.FieldPromptTokens:
		return m.AddedPromptTokens()
	case node.FieldCompletionTokens:
		return m.AddedCompletionTokens()
	case node.FieldTotalTokens:
		return m.AddedTotalTokens()
	case node.FieldCacheCreationInputTokens:
		return m.AddedCacheCreationInputTokens()
	case node.FieldCacheReadInputTokens:
		return m.AddedCacheReadInputTokens()
	case node.FieldTotalDurationNs:
		return m.AddedTotalDurationNs()
	case node.FieldPromptDurationNs:
		return m.AddedPromptDurationNs()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *NodeMutation) AddField(name string, value ent.Value) error {
	switch name {
	case node.FieldPromptTokens:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPromptTokens(v)
		return nil
	case node.FieldCompletionTokens:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCompletionTokens(v)
		return nil
	case node.FieldTotalTokens:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddTotalTokens(v)
		return nil
	case node.FieldCacheCreationInputTokens:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCacheCreationInputTokens(v)
		return nil
	case node.FieldCacheReadInputTokens:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCacheReadInputTokens(v)
		return nil
	case node.FieldTotalDurationNs:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddTotalDurationNs(v)
		return nil
	case node.FieldPromptDurationNs:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPromptDurationNs(v)
		return nil
	}
	return fmt.Errorf("unknown Node numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *NodeMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(node.FieldParentHash) {
		fields = append(fields, node.FieldParentHash)
	}
	if m.FieldCleared(node.FieldBucket) {
		fields = append(fields, node.FieldBucket)
	}
	if m.FieldCleared(node.FieldType) {
		fields = append(fields, node.FieldType)
	}
	if m.FieldCleared(node.FieldRole) {
		fields = append(fields, node.FieldRole)
	}
	if m.FieldCleared(node.FieldContent) {
		fields = append(fields, node.FieldContent)
	}
	if m.FieldCleared(node.FieldModel) {
		fields = append(fields, node.FieldModel)
	}
	if m.FieldCleared(node.FieldProvider) {
		fields = append(fields, node.FieldProvider)
	}
	if m.FieldCleared(node.FieldAgentName) {
		fields = append(fields, node.FieldAgentName)
	}
	if m.FieldCleared(node.FieldStopReason) {
		fields = append(fields, node.FieldStopReason)
	}
	if m.FieldCleared(node.FieldPromptTokens) {
		fields = append(fields, node.FieldPromptTokens)
	}
	if m.FieldCleared(node.FieldCompletionTokens) {
		fields = append(fields, node.FieldCompletionTokens)
	}
	if m.FieldCleared(node.FieldTotalTokens) {
		fields = append(fields, node.FieldTotalTokens)
	}
	if m.FieldCleared(node.FieldCacheCreationInputTokens) {
		fields = append(fields, node.FieldCacheCreationInputTokens)
	}
	if m.FieldCleared(node.FieldCacheReadInputTokens) {
		fields = append(fields, node.FieldCacheReadInputTokens)
	}
	if m.FieldCleared(node.FieldTotalDurationNs) {
		fields = append(fields, node.FieldTotalDurationNs)
	}
	if m.FieldCleared(node.FieldPromptDurationNs) {
		fields = append(fields, node.FieldPromptDurationNs)
	}
	if m.FieldCleared(node.FieldProject) {
		fields = append(fields, node.FieldProject)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *NodeMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *NodeMutation) ClearField(name string) error {
	switch name {
	case node.FieldParentHash:
		m.ClearParentHash()
		return nil
	case node.FieldBucket:
		m.ClearBucket()
		return nil
	case node.FieldType:
		m.ClearType()
		return nil
	case node.FieldRole:
		m.ClearRole()
		return nil
	case node.FieldContent:
		m.ClearContent()
		return nil
	case node.FieldModel:
		m.ClearModel()
		return nil
	case node.FieldProvider:
		m.ClearProvider()
		return nil
	case node.FieldAgentName:
		m.ClearAgentName()
		return nil
	case node.FieldStopReason:
		m.ClearStopReason()
		return nil
	case node.FieldPromptTokens:
		m.ClearPromptTokens()
		return nil
	case node.FieldCompletionTokens:
		m.ClearCompletionTokens()
		return nil
	case node.FieldTotalTokens:
		m.ClearTotalTokens()
		return nil
	case node.FieldCacheCreationInputTokens:
		m.ClearCacheCreationInputTokens()
		return nil
	case node.FieldCacheReadInputTokens:
		m.ClearCacheReadInputTokens()
		return nil
	case node.FieldTotalDurationNs:
		m.ClearTotalDurationNs()
		return nil
	case node.FieldPromptDurationNs:
		m.ClearPromptDurationNs()
		return nil
	case node.FieldProject:
		m.ClearProject()
		return nil
	}
	return fmt.Errorf("unknown Node nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *NodeMutation) ResetField(name string) error {
	switch name {
	case node.FieldParentHash:
		m.ResetParentHash()
		return nil
	case node.FieldBucket:
		m.ResetBucket()
		return nil
	case node.FieldType:
		m.ResetType()
		return nil
	case node.FieldRole:
		m.ResetRole()
		return nil
	case node.FieldContent:
		m.ResetContent()
		return nil
	case node.FieldModel:
		m.ResetModel()
		return nil
	case node.FieldProvider:
		m.ResetProvider()
		return nil
	case node.FieldAgentName:
		m.ResetAgentName()
		return nil
	case node.FieldStopReason:
		m.ResetStopReason()
		return nil
	case node.FieldPromptTokens:
		m.ResetPromptTokens()
		return nil
	case node.FieldCompletionTokens:
		m.ResetCompletionTokens()
		return nil
	case node.FieldTotalTokens:
		m.ResetTotalTokens()
		return nil
	case node.FieldCacheCreationInputTokens:
		m.ResetCacheCreationInputTokens()
		return nil
	case node.FieldCacheReadInputTokens:
		m.ResetCacheReadInputTokens()
		return nil
	case node.FieldTotalDurationNs:
		m.ResetTotalDurationNs()
		return nil
	case node.FieldPromptDurationNs:
		m.ResetPromptDurationNs()
		return nil
	case node.FieldProject:
		m.ResetProject()
		return nil
	case node.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown Node field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *NodeMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.parent != nil {
		edges = append(edges, node.EdgeParent)
	}
	if m.children != nil {
		edges = append(edges, node.EdgeChildren)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *NodeMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case node.EdgeParent:
		if id := m.parent; id != nil {
			return []ent.Value{*id}
		}
	case node.EdgeChildren:
		ids := make([]ent.Value, 0, len(m.children))
		for id := range m.children {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *NodeMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedchildren != nil {
		edges = append(edges, node.EdgeChildren)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *NodeMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case node.EdgeChildren:
		ids := make([]ent.Value, 0, len(m.removedchildren))
		for id := range m.removedchildren {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *NodeMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedparent {
		edges = append(edges, node.EdgeParent)
	}
	if m.clearedchildren {
		edges = append(edges, node.EdgeChildren)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *NodeMutation) EdgeCleared(name string) bool {
	switch name {
	case node.EdgeParent:
		return m.clearedparent
	case node.EdgeChildren:
		return m.clearedchildren
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *NodeMutation) ClearEdge(name string) error {
	switch name {
	case node.EdgeParent:
		m.ClearParent()
		return nil
	}
	return fmt.Errorf("unknown Node unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *NodeMutation) ResetEdge(name string) error {
	switch name {
	case node.EdgeParent:
		m.ResetParent()
		return nil
	case node.EdgeChildren:
		m.ResetChildren()
		return nil
	}
	return fmt.Errorf("unknown Node edge %s", name)
}
